config/routes.rb
Rails.application.routes.draw do
 
  root 'browse#index'
  resources :posts

  resources :browse, only: :index do
    get :authors, on: :collection
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true
  validates :category, presence: true
  validates :publish_date, presence: true
  validates :author, presence: true
  validates :text, presence: true

  before_create :set_random_rating

  scope :by_rating, -> (from, to) do
    to = 5 if to.blank?
    range = Range.new from.to_f, to.to_f
    where rating: range
  end

  scope :by_date, -> (date) do
    date_from = DateTime.parse date
    date_to = date_from + 1.day - 1.second
    range = date_from..date_to
    where publish_date: range
  end

  def set_random_rating
    self.rating = rand(0.0..5.0).round(2)
  end

  class << self
    def top_authors
      Post.order('average_rating desc').group(:author).average(:rating)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  POSTS_LIMIT = 10

  def index
    @posts = Post.includes(:category).order(rating: :desc).limit POSTS_LIMIT  
    filter_posts if params[:filter]
  end

  def authors
    @authors = Post.top_authors
  end

  private

  def filter_posts
    filter = params[:filter]
    @posts = @posts.where category_id: filter[:category]                unless filter[:category].blank?
    @posts = @posts.where author: filter[:author]                       unless filter[:author].blank?
    @posts = @posts.by_date filter[:publish_date]                       unless filter[:publish_date].blank?
    @posts = @posts.by_rating filter[:rating_from], filter[:rating_to]  unless filter[:rating_from].blank? and filter[:rating_to].blank?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes post_params
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path, status: 303
  end

  private

  def post_params
    params.require(:post).permit(:title, :category_id, :publish_date, :author, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def modal_window options
    content_tag :div, id: options[:id], class: 'modal' do
      content_tag :div, class: 'modal-dialog' do
        content_tag :div, class: 'modal-content' do
          header = content_tag :div, class: 'modal-header' do
            title = content_tag :h4, class: 'modal-title' do
              options[:title]
            end
            button = content_tag :button, class: 'close', data: { dismiss: 'modal' },  type: 'button' do
              "×"
            end
            "#{button} #{title}".html_safe
          end
          body = content_tag :div, class: 'modal-body' do
            options[:body]
          end
          "#{header} #{body}".html_safe
        end
      end
    end
  end

end

app/views/browse/_authors.html.haml
- unless @authors.empty?
  .col-md-12
    %table.table.table-bordered.table-striped
      %tr
        %th Author
        %th AVG Rating
      - @authors.each do |author|
        %tr
          %td
            %b= author[0]
          %td
            %span.badge= author[1].round(2)

app/views/browse/_list.html.haml
- posts.each do |post|
  .post-holder
    .panel.panel-success
      .panel-heading
        = post.title
        = " - [#{post.category.title}]"
      .panel-body
        %p= post.text
        .small.pull-left= post.author
        .pull-right.badge= post.rating

app/views/browse/index.html.haml
.panel.panel-default.panel-filter
  .panel-body
    - params[:filter] ||= {}
    = simple_form_for :filter, url: browse_index_path, method: :get, remote: true, defaults: { required: false }, html: { class: 'form-inline' } do |f|
      = f.input :author, input_html: { value: params[:filter][:author] }
      = f.input :category, collection: Category.all, selected: params[:filter][:category], include_blank: true
      = f.input :publish_date, input_html: { value: params[:filter][:publish_date], class: :datepicker }
      = f.input :rating_from, input_html: { value: params[:filter][:rating_from] }
      = f.input :rating_to, input_html: { value: params[:filter][:rating_to] }
      = f.submit 'Filter', class: 'btn btn-success'
      = link_to "Top authors", authors_browse_index_path, class: 'btn btn-info', remote: true

#browse_content.row
  = render 'list', posts: @posts

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Blog"
    = csrf_meta_tags
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    #modal_holder
    = render 'shared/menu'
    .container
      = yield

app/views/posts/_form.html.haml
= horizontal_form_for @post, remote: true do |f|
  = f.input :title
  = f.association :category
  = f.input :publish_date
  = f.input :author
  = f.input :text

  = f.button :submit, class: 'btn-success pull-right'

.clear

app/views/posts/_table.html.haml
- unless posts.empty?
  %table.table.table-bordered.table-striped
    %tr
      %th Title
      %th author
      %th Rating
      %th Actions
    - posts.each do |post|
      %tr
        %td= post.title
        %td= post.author
        %td= post.rating.round(2)
        %td
          .btn-group
            = link_to 'edit', edit_post_path(post), class: 'btn btn-xs btn-default btn-success', remote: true
            = link_to 'delete', post_path(post), method: :delete, class: 'btn btn-xs btn-default btn-danger', remote: true, data: { confirm: 'Sure?' }

app/views/posts/edit.html.haml
.row
  .col-md-6
    .panel.panel-success
      .panel-heading Edit post
      .panel-body
        = render 'form'

app/views/posts/index.html.haml
= link_to new_post_path, class: 'btn btn-primary', remote: true do
  %i.glyphicon.glyphicon-plus
  = "Create"
%br
%br

#posts-table
  = render 'table', posts: @posts

app/views/posts/new.html.haml
.row
  .col-md-6
    .panel.panel-primary
      .panel-heading Create new post
      .panel-body
        = render 'form'

app/views/shared/_menu.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    %a.navbar-brand Sample Blog Application
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to browse_index_path do 
            %i.glyphicon.glyphicon-eye-open
            = "Browse posts"
        %li
          = link_to posts_path do 
            %i.glyphicon.glyphicon-pencil
            = "Manage posts"